# `sudo:false` for faster builds.
sudo: false
language: node_js
cache:
  directories:
    - "node_modules"

.disable_global: &disable_global
  after_success: false
  after_failure: false
  deploy: false

.integration: &integration
  <<: *disable_global
  stage: integration
  # Needed for Firefox
  before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - sleep 3 # give xvfb some time to start
  script: script/run-integration-test.sh

# env forces jobs to be created from the top level settings
env:
jobs:
  include:
    - <<: *disable_global
      stage: moban
      language: python
      python: 3.6
      cache: pip
      before_install: false
      install: pip install moban
      before_script: false
      script: .ci/check_moban.sh
    - *integration
  allow_failures:
    - *integration

before_install:
  - npm install --no-save --no-optional --only=dev npm@5.8.0

install:
  - npm install --no-save --no-optional

script:
  # bufferstream in package-lock.json means optional dependencies
  # have been included.
  - if grep bufferstream package-lock.json ; then false; fi
  - script/build.sh
  - npm run test

after_success:
  - codecov

after_failure:
  - codecov

notifications:
  email: false
  webhooks: https://www.travisbuddy.com/
  on_success: never

# Remove /dist/ from .gitignore
before_deploy:
  - sed -i '/dist\//d' ./.gitignore

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
